move to nom7
adwhit/tokio-stomp pull request #16
Opened 2023-12-08 09:40 UTC by zuisong

- move to nom7 🥳
- upgrade deps

2023-12-10 14:18 UTC, adwhit commented
Hi - thanks for this.

I just pulled your changes and tried to run the `connect.rs` example against activemq docker and unfortunately I got parser failures. Does the same happen for you?

2023-12-10 14:38 UTC, zuisong commented
The tests I conducted under RabbitMQ ran smoothly. Let me try running them under ActiveMQ and see how it performs.

2023-12-10 14:50 UTC, zuisong commented
I have tested it under the following container, and it is running normally.
`docker run --detach --name activemq-artemis  --network=host  --rm apache/activemq-artemis:latest-alpine`

default username and password is `artemis` 
It is possible that the account credentials you used for the connection were incorrect.

2023-12-10 15:07 UTC, zuisong commented
I have reproduced this issue with `apache/activemq-classic` image.

server return CONNECTED frame with
```
CONNECTED
server:ActiveMQ/6.0.0
heart-beat:0,0
session:ID:orbstack-45879-1702220142549-3:2
version:1.2

```
In the STOMP protocol specification, colons are not allowed.
```
header-name         = 1*<any OCTET except CR or LF or ":">
header-value        = *<any OCTET except CR or LF or ":">
```


Perhaps we should consider accommodating this situation?

2023-12-11 02:53 UTC, zuisong commented
@adwhit  I have added code to handle this situation. Please try again.

2023-12-11 09:14 UTC, adwhit commented on src/frame.rs
> +pub fn parse_frame(input: &[u8]) -> IResult<&[u8], Frame> {
this should be `pub(create)`

2023-12-11 09:17 UTC, adwhit requested changes
Interesting that the 'classic' docker image is in violation of the spec - nevertheless I think it is good to be permissive so thank you for the fix.

Just one comment then we should be good to merge

2023-12-11 09:23 UTC, adwhit commented on src/client.rs
> +    server: impl Into<String>,
this should be `impl ToSocketAddrs`

2023-12-11 09:24 UTC, adwhit commented on src/client.rs
>      let addr = address.as_str().to_socket_addrs().unwrap().next().unwrap();
rather than `unwrap()`, this should return an error if it the conversion fails

2023-12-11 10:10 UTC, zuisong commented
It should be fixed now. 😄

2023-12-11 11:22 UTC, merged

2023-12-11 11:23 UTC, adwhit commented
Thanks!

2023-12-11 11:31 UTC, adwhit commented
This PR has been released as `v0.4.0`